# Netlify configuration for Activity Log UI
[build]
  # Generate config.js from environment variables
  command = "node build-config.js"
  # Directory containing the deploy-ready assets
  publish = "."

[build.environment]
  # Set these in Netlify UI:
  # WORKER_URL = "https://your-worker.workers.dev"
  # AUTH_TOKEN = "your-auth-token"
