name = "web-chronicle-ui"
main = "./worker.js"
compatibility_date = "2024-07-06"

[assets]
directory = "./"
exclude = ["node_modules", "wrangler.toml", "worker.js", "package*.json", ".wrangler", ".git*", "*.md"]