name = "web-chronicle-next"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NODE_VERSION = "20"

# Production environment settings
[env.production]
compatibility_flags = ["nodejs_compat"]
vars = { NODE_VERSION = "20" }