name = "web-chronicle-ui"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[site]
bucket = "./out"

[[routes]]
pattern = "/*"
zone_name = "your-domain.com"

# Environment variables are set in Cloudflare dashboard
# or during deployment with --var flags